#!/bin/bash
#
#PBS -l walltime=01:00:00
#PBS -l nodes=1:ppn=12:golub
#PBS -N nn-vary-nodes
#PBS -q secondary
#
# End of embedded QSUB options
#

# execute in my virtual env
source /home/limjiaj2/bitcoin-deanonymization/venv/bin/activate

# change to bitcoin dir
cd /home/limjiaj2/bitcoin-deanonymization

# load necessary modules
module load python/2
module load gcc/6.2.0


# Run fully_connected_feed.py un varied h2 vals
/home/limjiaj2/bitcoin-deanonymization/nn-h2-nodes.sh
